### ISSUE TITLE
Cutoff frequency for the RC filter

### ISSUE THREAD

**Issue by pmaroti** [dawsonjon/101Things#3]
Hi, it seems with the given RC values the IQ filter has a very low cutoff frequency around 300 Hz instead of 3kHz.

**Comment by dawsonjon** [comment]
Hi, thank you very much for getting in touch! I can't quite spot the error you are referring to. Please could you let me know which component values you mean?

**Comment by pmaroti** [comment]
In case of the original transmitter circuit the pico outputs IQ amplitude signal as a pwm signal and filtered with a simple RC filter (220 ohm & 220nF). As I calculate the cutoff frequency will be around 300 Hz and not 3 Khz.

**Comment by pmaroti** [comment]
Sorry my mistake the filter with 220nF and 220ohm has a cutoff frequency with 3.290 Hz...
